### ISSUE TITLE
Default selected index

### ISSUE THREAD

**Issue by CatchZeng** [sergik-ru/SMTabbedSplitViewController#3]
How can I set default selected index about tabbar? some function like selectedIndex:(int)index

**Comment by sergik-ru** [comment]
By default similar function doesn't exist. 
You can change default selected tab in the SMTabBar.m file, in method `- (void)tabsInit:(NSArray *)tabs`, changing the line 78 `NSIndexPath * firstTab = [NSIndexPath indexPathForRow: 0 inSection: 0];` (change row). Or create method for that.
