### ISSUE TITLE
Tab Bar Badge Value 

### ISSUE THREAD

**Issue by mubasherkhan** [sergik-ru/SMTabbedSplitViewController#5]
I have set tab bar badge value but it is not showing on view 
`    tab1VC.tabBarItem.badgeValue=@"100";
`
Does SMTabBar lacks badgeValue property ?If it is so how can i gain this property .

**Comment by sergik-ru** [comment]
Hi, thx for question, but badges don't supported in this version.

**Comment by mubasherkhan** [comment]
Can it be customized ?

**Comment by sergik-ru** [comment]
Yes, you need implement it in SMTabBarItem and SMTabBarItemCell
